context:
  version: "679"

package:
  name: less
  version: ${{ version }}

source:
  url: https://greenwoodsoftware.com/less/less-${{ version }}.tar.gz
  sha256: 9b68820c34fa8a0af6b0e01b74f0298bcdd40a0489c61649b47058908a153d78
build:
  number: 2
  script:
    - if: win
      then:
        - nmake -f Makefile.wnm
        - mkdir %PREFIX%\bin
        - copy less.exe %PREFIX%\bin\
        - copy lesskey.exe %PREFIX%\bin\
      else:
        - ./configure --prefix=${PREFIX} --with-regex=pcre2
        - make
        - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: unix
      then:
        - autoconf
        - make

  host:
    - if: unix
      then:
        - ncurses
        - pcre2

tests:
  - script:
      - less --version
      - lesskey --version
      - ${{ "lessecho --version" if unix }}

about:
  summary: A terminal based program for viewing text files
  description: |
    Less is a pager. A pager is a program that displays text files. Other pagers
    commonly in use are more and pg. Pagers are often used in command-line
    environments like the Unix shell and the MS-DOS command prompt to display
    files.
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - COPYING
  homepage: https://www.greenwoodsoftware.com/less
  repository: https://github.com/gwsw/less
  documentation: https://www.greenwoodsoftware.com/less/faq.html

extra:
  recipe-maintainers:
    - tetov
